apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsnew
spec:
  replicas: 5
  selector:
    matchLabels:
      type: nginx
  template:
    metadata:
      name: pod1
      labels:
        type: nginx
    spec:
      containers:
      - name: mycontainer
        image: httpd
        ports:
        - containerPort: 80
          name: http

---

apiVersion: v1
kind: Service
metadata:
  name: rsnew
spec:
  type: ClusterIP
  selector:
    type: nginx
  ports:
  - port: 80
    targetPort: 80
